[package]
name = "merge"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"

[dev-dependencies]
criterion = "0.5"

[profile.bench]
opt-level = 3
lto = "thin"
codegen-units = 1
debug = false